import Head from 'next/head'
import { Inter } from '@next/font/google'
import { verifyToken } from './api/auth/authToken'
import { useState } from "react"
import Posts from "@/components/Posts"

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps(ctx){  
  const verify = await verifyToken(ctx)

  if(!verify) return { props: {}}
  
  const reqPosts = await fetch(`${process.env.PUBLIC_API_URL}/api/posts?populate[user][populate]=image&populate[likedBy]=*&populate[image]=*&populate[comments][populate][user][populate][0]=image&populate[comments][populate][replies][populate][user][populate][0]=image`, {
      headers: {
          "Authorization": "Bearer " + verify
      }
  })
  const resPosts = await reqPosts.json()

  const sevenDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).getTime(); 
  const filtered = resPosts.data.filter(post => {
    const postCreatedDate = new Date(post.attributes.createdAt).getTime();
    return postCreatedDate >= sevenDaysAgo
  })

  return {
      props: {
          posts: filtered ? filtered : [],
          token: verify,
      }
  }
}

export default function Home({posts, token, currentUser}) {
  const [postsApi, setPostsApi] = useState(posts); 

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div>
            <Posts data={{postsApi, token, currentUser}} />
      </div>
    </>
  )
}

