import Head from "next/head";
import { verifyToken } from "./api/auth/authToken";

export async function getServerSideProps(ctx){  
    const verify = await verifyToken(ctx)
  
    if(!verify) return { props: {}}
  
    return {
        props: {
            token: verify,
        }
    }
  }

export default function notification({token, currentUser}) {
  return (
    <>
        <Head>
           <title>Notification</title>
           <meta name="description" content="Generated by create next app" />
           <meta name="viewport" content="width=device-width, initial-scale=1" />
           <link rel="icon" href="/favicon.png" />
        </Head>
        <div className="min-h-[80vh] flex justify-center items-center">
            <div className="border border-dashed px-20 py-4 text-text-third border-text-third">Coming Soon</div>
        </div>
    </>
  )
}
