import { useState } from "react"
import Link from "next/link"
import { authToken } from "./api/auth/authToken"
import Router from "next/router"
import Image from "next/image"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faSpinner } from "@fortawesome/free-solid-svg-icons"
import Head from "next/head"

export async function getServerSideProps(ctx){
    const verify = await authToken(ctx)

    return {
        props: {}
    }
}

export default function Register() {
  const [field, setField] = useState({})
  const [loading, setLoading] = useState(false) 
  const [success, setSuccess] = useState(false)
  const [message, setMessage] = useState("")

  const registerHandler = async (e) => {
    e.preventDefault();
    setLoading(true)
    const reqRegister = await fetch(`${process.env.PUBLIC_API_URL}/api/auth/local/register`, {
        method: "POST",
        headers: {
            "Content-Type": "Application/json"
        },
        body: JSON.stringify(field)       
    })

    const resRegister = await reqRegister.json()
    if(resRegister.jwt){
        e.target.reset()
        setSuccess(true)
        
        setTimeout(() => {
            setSuccess(false)
            Router.push("/login")
        }, 1000)
    }
    setMessage(resRegister.error?.message)
    setLoading(false)
} 
  
  const fieldHandler = (e) => {
    const {name, value} = e.target;
    setField({
        ...field,
        [name]: value
    })
  }

  return (
    <>
    <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
    </Head>
    <form onSubmit={registerHandler} className="mx-auto flex top-0 bottom-0 left-0 right-0 w-full fixed z-[50] items-center text-text-primary flex-wrap min-h-screen justify-center py-10 bg-bg-primary">
            <div className="flex border-2 border-double border-border-primary rounded-md max-w-full py-5 sm:py-0">
                <div className={`bg-green-500 fixed ${success ? "z-10" : "-z-10"} transition-all duration-300 ${success ? "translate-y-20" : "-translate-y-full"} max-w-[390px] mx-auto -top-10 rounded-lg left-10 px-4 py-4 right-10 justify-between flex items-center`}>Your Account has been registered! <span onClick={() => setSuccess(false)} className="text-lg font-bold cursor-pointer px-[4px] rounded-sm">&#10005;</span></div>
                <div className="flex flex-wrap content-center justify-center rounded-l-md w-[384px] h-[512]">
                    <div className="w-72">
                        <h1 className="text-xl font-semibold">Register</h1>
                        <small className="text-text-third">Welcome! Please enter your details</small>

                        <div className="mb-3 mt-4">
                            <label className="mb-2 block text-xs font-semibold">Username</label>
                            <input  autoComplete="off" type="text" placeholder="Username" className="block w-full rounded-md border bg-bg-primary border-border-secondary focus:border-header-primary focus:outline-none focus:ring-1 focus:ring-header-primary py-1 px-1.5" name="username" onChange={fieldHandler} required />
                        </div>

                        <div className="mb-3">
                            <label className="mb-2 block text-xs font-semibold">Email</label>
                            <input autoComplete="off" type="text" placeholder="Email" className="block w-full bg-bg-primary rounded-md border border-border-secondary focus:border-header-primary focus:outline-none focus:ring-1 focus:ring-header-primary py-1 px-1.5" name="email" onChange={fieldHandler} required />
                        </div>


                        <div className="mb-3">
                            <label className="mb-2 block text-xs font-semibold">Password</label>
                            <input autoComplete="off" type="password" placeholder="*****" className="block w-full rounded-md border bg-bg-primary border-border-secondary focus:border-header-primary focus:outline-none focus:ring-1 focus:ring-header-primary py-1 px-1.5" name="password" onChange={fieldHandler} required />
                        </div>

                        <div className="mb-3">
                            <p className="text-red-500 text-sm">{message}</p>
                        </div>

                        <div className="mb-3">
                            <button disabled={loading} type="submit" className="mb-1.5 block w-full text-center bg-header-primary hover:bg-blue-800 px-2 py-1.5 rounded-md">
                            {loading ? (
                                <>
                                    <FontAwesomeIcon icon={faSpinner} className="animate-spin" /> Loading...
                                </>
                            ): (
                                <p>Register</p>
                            )}
                            </button>
                        </div>

                        <div className="text-center">
                        <span className="text-xs text-text-third font-semibold">Already have an account?</span>
                        <Link href="/login" className="text-xs font-semibold text-header-primary ml-1">Login</Link>
                        </div>
                    </div>
                </div>

                <div className={`sm:flex hidden flex-wrap content-center justify-center rounded-r-md w-[384px] h-[512px] relative`}>
                    <Image className="w-full h-full bg-center bg-no-repeat bg-cover rounded-r-md" src="https://i.imgur.com/9l1A4OS.jpeg" fill />
                </div>
            </div>
        </form>
    </>
  )
}
